server:
  port: 8081
spring:
  application:
    name: auth-service
  config:
    import:
      - "optional:classpath:eureka-client.yaml"
      - "optional:classpath:grpc-client.yaml"
      - "optional:classpath:spring-doc.yaml"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/profitability_auth}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: "9a4f4c35456584c35063138072105151241121112413151235346314151617181920"
  expiration: 86400000
