spring:
  cloud:
    gateway.server.webflux:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "https://profit.hakolr.dev"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - Accept
              - X-Auth-User-Id
              - X-Auth-User-Role
              - X-Pinggy-No-Screen
              - Ngrok-skip-browser-warning
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true # Позволяет шлюзу создавать маршруты на основе имен в Eureka
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: investment-service
          uri: lb://investment-service
          predicates:
            - Path=/api/investment/**
        - id: cbr-service
          uri: lb://cbr-service
          predicates:
            - Path=/api/cbr/**
